### ISSUE TITLE
Request to add Abhishek Gupta to Speakers page

### ISSUE THREAD

**Issue by atg-abhishek** [Green-Software-Foundation/speakers#1]
Hi! I'd love to get myself listed on the speakers page; [here](https://www.youtube.com/watch?v=wIC2Za8hHuE&t=2s) is an example of a talk I've given on the subject. Thanks!

**Comment by holanita** [comment]
Hi @atg-abhishek sorry for the late reply, we haven't started using this repo and the new website for managing applications yet. We are in the process of setting up the website, so for the time being we are accepting applications via google docs. I'll send you an email to confirm next steps. Thanks for your interest!

**Comment by holanita** [comment]
Hi again @atg-abhishek hope you received my email. Let me close this task and let's continue the conversation via email as we are still in the process of building both the site and our GitHub PM structure for this project.
