### ISSUE TITLE
[Setup] add contact forms for speakers

### ISSUE THREAD

**Issue by holanita** [Green-Software-Foundation/speakers#11]
As per our initial discussions with Asim, there will be an application form on the website for new speakers who want to join. 
Also, we might want to create another simple form for those who already have a profile, but would like to update something in it.

**Comment by osamajandali** [comment]
I need more details regarding where it should be on the website and what field need to include and where the submitted data should go

**Comment by holanita** [comment]
- I would leave the placement up to you guys. I'd prefer to create a separate page for this form due to its complexity.
- We have to include all the fields we have in the speaker profile, as the idea is to get all the data from them in one go.
- One more extra field we need for sure: email address (so we can contact them).
- And maybe a checkbox too so they can indicate they agree that their data will be published on the website.
- Can it be added as an issue / PR automatically? If not, you can have it emailed to me directly and I'll handle it manually.

**Comment by jawache** [comment]
I would suggest a google form.

@osamajandali have a button in the top menu, "apply as as speaker"

**Comment by holanita** [comment]
I just figured it would be nice to use google forms for this one as well. Having an excel spreadsheet with all the form responses would make it easier to create stats and reports about the project. Not sure if this would be possible with GH/Docusaurus? All the speaker data would be published (and transparent) anyways as soon as a profile is uploaded. What do you think @jawache ?

**Comment by holanita** [comment]
@jawache does google form work for you or shall we stick to issues?

**Comment by jawache** [comment]
@holanita what ever works best for you.

**Comment by zanete** [comment]
@holanita , I suggest we do the same her as for the event organisers form. Once you have a google form, please add the link to it that needs to be added to the website into this issue: https://github.com/Green-Software-Foundation/speakers/issues/26
what do you think?

**Comment by holanita** [comment]
Okay, I have the form already (in draft version). 'm closing this off now.
