### ISSUE TITLE
[Setup] add contact forms for event organizers

### ISSUE THREAD

**Issue by holanita** [Green-Software-Foundation/speakers#12]
Our idea is that if someone wants to get in touch with a speaker to request a speech, they should submit their request using a contact form on the speaker's profile page. We will not disclose the speaker's email address. The message should be emailed to the speaker and GSF automatically. We should keep a log of all these messages to be able to follow up and track stats.

Sub-Tasks:
- [x] Asim to confirm what fields this contact form should have (name, company, email, message might be enough)
- [x] Anita to fine-tune [the google form](https://docs.google.com/forms/d/e/1FAIpQLSd6jJm3Pt32dkYxQxhu4V-WXO4KP81LB0v-0bmd9oL_KlQ8bQ/viewform) as needed 
- [ ] Osama to create button / add the link to the website

**Comment by holanita** [comment]
@jawache pls check if this looks ok to you and let us know if you have anything else to add

**Comment by jawache** [comment]
Contact details.
Event Name
Language
Location
Dates

Are you requesting a specific speaker or do you want to share a Call For Papers?

- If it's a specific speaker please give us their name,

- If it's a CFP please provide details.

- If you'd like to speak to us about something that's covered above click this checkbox.


One google form with a link at the top of the website. "I'm looking for a speaker"

**Comment by holanita** [comment]
Let's use this form. I'll tweak it later, but you can already use the url to create the button:
https://forms.gle/URMS5XtMqYAAT8cL6

**Comment by holanita** [comment]
@jawache please let me know when you have an ETA for this

**Comment by jawache** [comment]
@holanita yes let's add that form to the website.

**Comment by zanete** [comment]
@holanita @jawache I will consider this issue to be about the form creation only and then adding to the website is handled as part of https://github.com/Green-Software-Foundation/speakers/issues/26, so we can consider this as done.

**Comment by zanete** [comment]
oh, @holanita, my apologies. I closed this off prematurely as there's a bunch of other tasks in the description for things that are not just the form. Do I understand correctly the only thing hat is needed from Osama is to add that form link to the speaker website? and the rest of the tasks - are they for Asim or for you?

**Comment by holanita** [comment]
@zanete no worries, I have quickly closed off all the other tasks and fine-tunes the form. If you prefer to use the other issue with Osama, feel free to close this off now. I'll leave it up to you. Whatever works best.
