### ISSUE TITLE
[Bug] video preview 

### ISSUE THREAD

**Issue by holanita** [Green-Software-Foundation/speakers#14]
https://github.com/Green-Software-Foundation/speakers/blob/5c2abf61ba9cf3d743146ee2e3ca18aefec31aac/docs/speakers/bill-johnson.mdx?plain=1#L38

@osamajandali for this video, the url points to the 2721st second. when I click on the title, it takes me to the right spot, but the video preview on our website starts from the very beginning not from the 2721st second.

**Comment by osamajandali** [comment]
Fixed

**Comment by holanita** [comment]
Thank you @osamajandali !
