### ISSUE TITLE
[SPKR] add disclaimer to top banner

### ISSUE THREAD

**Issue by holanita** [Green-Software-Foundation/speakers#22]
add a top banner to the website to explain that speakers are supposed to give talks at professional events, but they are not supposed to represent the GSF in the media etc. if someone is looking for a GSF representative, they should contact helpdesk@greensoftware.foundation (?) TBC

@jawache what should be the exact text?

**Comment by holanita** [comment]
@jawache just a reminder about this. what should be the exact text and how shall Osama implement this exactly?

**Comment by zanete** [comment]
@jawache another reminder to provide input here or please direct me where that can otherwise be obtained? Is this a matter of preparing copy that appears everywhere on the side / on landing page only?

**Comment by zanete** [comment]
Given how difficult it is to get Asim's attention on this, @holanita how about we use this space here for that text? 

![Image](https://user-images.githubusercontent.com/35653799/199247080-5cbde71d-88a2-4cca-b029-b782c6626c48.png)

or is there an expectation that it's more prominent?

Regarding the text, 
Is this meant to be some legal text in which case we would need to consult @seanmcilroy29 or a more friendly way to set the terms in which case we can consult @ursvill ?

**Comment by holanita** [comment]
@zanete to be honest, I feel like this is important enough to be placed in a top banner and to be visible on each page not just the main page. I can try to talk about this with Asim in our call tomorrow if time allows.

**Comment by holanita** [comment]
Okay, this has been added to all three contact forms we have on the website (add speaker, looking for speaker, contact us)
