### ISSUE TITLE
[Setup] Style speaker profiles on speakers website

### ISSUE THREAD

**Issue by zanete** [Green-Software-Foundation/speakers#25]
**Scope of work:**
- [x] investigate what can be done in terms of styling
- [x] review https://speakers.greensoftware.foundation/speakers/ and investigate how to make the data on the details page reflect the data types that are used in the form for each piece of data (e.g. if it's multiple choice, it should behave like that in the details) (Look at the form, every thing in the form that's NOT free text is a candidate for a tag.)
- [x] add a button that says "Contact speaker" takes to https://grnsft.org/speakers/find

**Comment by zanete** [comment]
@jawache please add the form that the speakers fill so Osama could be better informed about the data he's working with

**Comment by holanita** [comment]
@zanete is this a duplication of [my old issue](https://github.com/Green-Software-Foundation/speakers/issues/10)? shall I remove mine?

**Comment by jawache** [comment]
@holanita please can you provide @osamajandali the google form that you are using for people to signup, he's going to use that to understand how to structure the data on the website.

**Comment by jawache** [comment]
Copying in content from @holanita in the other ticket:

I'm not quite sure about the details, I just heard from Asim that you would still be working on the styling.

There is just one thing I'd suggest to change – the headings seem to be too big, bold and green. To me it feels like they distract the attention from the actual content too much. So just on the profile pages, I'd make them smaller than usual.

**Comment by zanete** [comment]
This should be fine for @osamajandali , thank you very much.

**Comment by holanita** [comment]
@osamajandali the new profiles look amazing. really like how you tweaked the videos and all the other fields as well. I'd say that we can close this now. let me know if you don't agree.
