### ISSUE TITLE
[Setup] Buttons on the top of the speakers website

### ISSUE THREAD

**Issue by zanete** [Green-Software-Foundation/speakers#26]
**Scope of work:**
- [x] "I'm looking for a speaker" button should be permanently added in the top nav for https://speakers.greensoftware.foundation/, redirects to https://grnsft.org/speakers/find
- [x] "I am a speaker" button should be permanently added in the top nav for https://speakers.greensoftware.foundation/, redirects to https://grnsft.org/speakers/apply

**Comment by zanete** [comment]
@jawache can we clarify where we can get the links to the forms? is this something @holanita could provide? 🙏

**Comment by holanita** [comment]
@zanete this seems to be related to the two issues I created earlier about adding forms. see the details here. I've been waiting for feedback on both issues for a while:
- https://github.com/Green-Software-Foundation/speakers/issues/11
- https://github.com/Green-Software-Foundation/speakers/issues/12

**Comment by holanita** [comment]
@osamajandali I have the urls for both forms already. Please see them below. 
[Apply as a speaker](https://docs.google.com/forms/d/e/1FAIpQLSd6jJm3Pt32dkYxQxhu4V-WXO4KP81LB0v-0bmd9oL_KlQ8bQ/viewform) (done, Sean to investigate issues with file upload)
[Looking for a speaker](https://docs.google.com/forms/d/e/1FAIpQLScNE_Mysxf8QSMb9aaki2Bvo8M8npqHjIaWHcZVpGIIQUCrAw/viewform) (draft, to be completed by Anita later)

**Comment by zanete** [comment]
@zanete to create some short links for these

**Comment by zanete** [comment]
@holanita I've created the following short links that will be added into the website (and then can be changed to whatever form is used should that change in the future)
- https://grnsft.org/speakers/find
- https://grnsft.org/speakers/apply

cc @jawache @osamajandali

**Comment by holanita** [comment]
OK noted. thank you.

**Comment by holanita** [comment]
This looks perfect now. Thanks @osamajandali
