### ISSUE TITLE
[Setup] Change logo on speakers website

### ISSUE THREAD

**Issue by zanete** [Green-Software-Foundation/speakers#27]
**Scope of work**:
- [x] Update the logo to that @Jenya-design created for the speakers project, should be found here https://drive.google.com/drive/folders/1HVSSE58F95-w2zPU8GeerEFk89BrDHjH or more info https://github.com/Green-Software-Foundation/ops-admin/issues/14

**Comment by holanita** [comment]
This looks perfect now so I'm closing this. Thanks @osamajandali !
