### ISSUE TITLE
[Setup] Display a list of all the speakers

### ISSUE THREAD

**Issue by jawache** [Green-Software-Foundation/speakers#29]
**Why**: The speakers catalogue will be announced around COP so the website needs to look presentable and user friendly
**What**: A way to see all speakers at a glance 
**Scope of Work**:
- [ ] Implement speaker overview (initially discussed in #16) to show up in https://speakers.greensoftware.foundation/speakers/  as a list of all speakers using autogenerated card components as can be seen in the main docusaurus site  https://docusaurus.io/docs/category/getting-started

**Comment by zanete** [comment]
@holanita I feel that would be a "nice-to-have" and perhaps worth raising another issue so that can be prioritised/tracked separately given how much is on the Web dev plate atm. what do you think?
