### ISSUE TITLE
Add new speakers to updated website

### ISSUE THREAD

**Issue by holanita** [Green-Software-Foundation/speakers#34]
@osamajandali I tried to add a new speaker profile but for some reason it didn't go through. I removed a couple of lines from the md file as they were blank. plus I added a previous talk that was text only with no link. unsure what caused the issue. can you help me figure out? see the failed action here: https://github.com/Green-Software-Foundation/speakers/actions/runs/3368332794

**Comment by holanita** [comment]
missing url on line 23 
or maybe this on line 19: <none specific> 
or the missing comma on line 28
can't think of anything else
https://github.com/Green-Software-Foundation/speakers/commit/b9254d03863eb422f5fccacab18c55e6ebdf02d7

**Comment by osamajandali** [comment]
It doesn't accept empty attributes. So if something is not available you should remove it.
So here the url is empty, it should be removed.
If you want to jump on a call to onboard you on the new structure let me know

**Comment by holanita** [comment]
OK I see. I gave it another time but it failed again. 
Can you take a look at this new code to see what is still wrong? https://github.com/Green-Software-Foundation/speakers/commit/a7441e683c3877460efb11f67ae272ed70a7b981
(I deleted the original file and created a new one with the same filename)

**Comment by osamajandali** [comment]
I added a comment in the code
and I fix it here [6ef14c3](https://github.com/Green-Software-Foundation/speakers/commit/6ef14c31da6ea41712ca066f651549a900b9ae4f)

**Comment by holanita** [comment]
thank you @osamajandali !
