### ISSUE TITLE
[SPKR] Document how to add/update speakers

### ISSUE THREAD

**Issue by zanete** [Green-Software-Foundation/speakers#35]
**Why**: Ensure that anyone in the GSF team are able to keep the speakers catalogue up to date
**What**: Produce documentation on how to manage speakers content
**Scope of work**: 
- [x] Describe (with screenshots) how to add a new speaker
- [x] Describe (+screenshots) how to edit an existing speaker
- [x] Document required vs optional fields
- [ ] Document any other relevant information for search/filtering to work etc 
- [ ] Deploy documentation to [Google doc](https://docs.google.com/document/d/1hNb2LrI9m7Q_oKLc0_ik304i2pZ28Yx4NECPxhYn9Rw/edit) 

cc @holanita

**Comment by holanita** [comment]
@zanete I have created [this guide](https://docs.google.com/document/d/1hNb2LrI9m7Q_oKLc0_ik304i2pZ28Yx4NECPxhYn9Rw/edit?usp=sharing) to document my workflow. Hope this helps.
@osamajandali When you have time please review this and add any other tips you might have. Thanks.

**Comment by zanete** [comment]
@holanita this ticket was added by me because @osamajandali indicated that since he's changing how the speakers are looking on the FE, it would be much easier if you moved away from the docusaurus solution. 

I assumed that will cause anything from here on: https://docs.google.com/document/d/1hNb2LrI9m7Q_oKLc0_ik304i2pZ28Yx4NECPxhYn9Rw/edit#heading=h.yi1efw58aab0 to change and we would need @osamajandali (when he has time, planned for last week of Nov) to describe the new way.

I could be wrong and will wait for @osamajandali to comment, but regardless, thank you for the document, 
- that's what Osama can use to put the information in, 
- and it's also very helpful to see the whole process there. 🙏

**Comment by zanete** [comment]
@holanita Another thing I wanted to clarify with this is, eventually, when the google doc is ready, would the documentation eventually have to move to another place online, such as the [playbook/handbook](https://handbook.greensoftware.foundation/)?

**Comment by holanita** [comment]
@zanete  okay
- the handbook has been created by Asim so I think you should ask him. I never had the time to check it thoroughly. 
- feel free to edit my file as needed. I wasn't aware that we were about to implement a third way of adding speakers.

**Comment by holanita** [comment]
@zanete yes, I've already caught up. If that's the most up-to-date way of doing things then my guide will be fine as it is.But it would still be nice if Osama could take a look after COP when he has time.

**Comment by zanete** [comment]
ook, thank you for clarifying! that's excellent news.

**Comment by holanita** [comment]
@osamajandali from time to time I seem to have issues with special characters as speakers often use them. so I've added to the doc that _when you have colon or any other special characters inside the text you need to wrap the text in quotes " "_ 

will this work for all the fields (except urls I guess)? 
are there any other similar rules that would be worth noting?

**Comment by osamajandali** [comment]
@holanita, it's a good idea to wrap every field in quotes to avoid errors.
The other rules are to have the indentation written and to add a dash (-) in the right place...those are the things that may cause problems.

I have added a template file in the root directory so anyone can duplicate this and put it inside the speaker folder to create a new one.
here is it https://github.com/Green-Software-Foundation/speakers/blob/main/SPEAKER_TEMPLATE.md

**Comment by holanita** [comment]
Great thanks @osamajandali I think this will be fine so I'm closing this ticket.
