### ISSUE TITLE
[SPKR] Fix Contact us link on speakers website

### ISSUE THREAD

**Issue by zanete** [Green-Software-Foundation/speakers#37]
**Steps to reproduce**:
- visit https://speakers.greensoftware.foundation/
- click on "Contact us" at the bottom

**Expected outcome**:
- [ ]  opens https://forms.gle/jL57mfDzTofHaRuC7 in new tab

**Actual outcome:**
- for some people opens mailto: link, for some - nothing happens.

cc @holanita

**Comment by osamajandali** [comment]
Fixed
