### ISSUE TITLE
[Setup] sidebar position, order of profiles

### ISSUE THREAD

**Issue by holanita** [Green-Software-Foundation/speakers#4]
https://github.com/Green-Software-Foundation/speakers/blob/935f019bc5f06f72a4f1bf066c8de79f47d8732a/docs/speakers/asim-hussain.mdx?plain=1#L2

@osamajandali @jawache do I have to set this manually every time I add a new profile? is there a way to show profiles in alphabetical order by default?

**Comment by jawache** [comment]
@osamajandali can you take a look, might need to customise the sidebar config or use something than the autogenerated plugin? https://docusaurus.io/docs/sidebar/autogenerated

**Comment by osamajandali** [comment]
I will work on it

**Comment by holanita** [comment]
Just figured that if I set the sidebar position to 1 for each profile, they will be ordered alphabetically. Looks perfect on the website now.

**Comment by osamajandali** [comment]
I feel that we can stick with keep using the sidebar position to 1 unless we want more advance thing then we use the autogenerated plugin
