### ISSUE TITLE
List upcoming conferences

### ISSUE THREAD

**Issue by holanita** [Green-Software-Foundation/speakers#44]
What: maintain a list of upcoming conferences where green software is on the agenda
Why: Asim mentioned that this could be a potential add-on to the speaker bureau and useful resource of everyone
When: this list is to be updated on an ongoing basis and will likely be added to the website in Stage 2

**Comment by holanita** [comment]
Recent suggestions:
- [QCon](https://qconferences.com/)
- [Devoxx](https://www.devoxx.co.uk/)
- [Kubecon](https://events.linuxfoundation.org/kubecon-cloudnativecon-europe/)
- [Srecon](https://www.usenix.org/srecon) (usenix)- may be too niche
- [Open Source Summit](https://events.linuxfoundation.org/open-source-summit-north-america/)

**Comment by Sealjay** [comment]
We should do Open Source Summit Europe https://events.linuxfoundation.org/open-source-summit-europe/ - I know @Willmish has submitted here too: https://events.linuxfoundation.org/embedded-open-source-summit/about/lf-energy-embedded-summit/

**Comment by gaelduez** [comment]
@greenhsu123 for API Days Singapore, London (and of course Paris but you already know that) dedicated Sustainability Track will be set up this year. I'll be actively involved in the London one (I will be in charge of the Sustainable Digital challenge 1st edition in the UK) and I know very well the person in charge of the Singapore one. Shall we sync re the speakers you've submitted?

**Comment by danuw** [comment]
Hi, any interest room for us to speak about the SDK and the Carbon Aware SDK / API at API Days - we can also cover London and Paris.
Aware that we will want to promote the latest version of the API for the Hackathon pre/for COP27 (though Hackathon not yet confirmed)
Please let @Willmish and me know and we will happily submit a talk then

**Comment by greenhsu123** [comment]
@gaelduez that sounds like a great idea! Let's set up a quick call to sync :) @danuw, we will bear in mind your proposal!

**Comment by gaelduez** [comment]
@greenhsu123 could you tell me who is the speaker you recruited for Apidays Singapore?

**Comment by amandhamija98** [comment]
Hi @gaelduez ! I will be speaking at Apidays Singapore

**Comment by gaelduez** [comment]
Hey @amandhamija98 , I didn't know wyou were part of GSF as well. Sorry of course you speak, Thibaut had already shared the information with me. Sorry about the mess with my questions. All good then. Let's focus on London and Paris (but the line-up is far from being discussed already)

**Comment by amandhamija98** [comment]
@gaelduez no worries at all! thank you

**Comment by vaughanknight** [comment]
Kubecon will have some carbon aware SDK goodness in the KEDA session.  Yassine will be presenting from what I understand (one of the original contributors to the CA SDK)

**Comment by LadyLowcode** [comment]
I will speak next week on Tech Summit Europe in Amsterdam 28th of March and also virtual at WeAreDevelopers World sustainability day. Could these be good contributions also for next year?

**Comment by greenhsu123** [comment]
@LadyLowcode, certainly! Thanks for sharing. 

@ioana-chiorean, we will make a note on JS HEROS and see if we can have someone join in the fun next year! Thanks for flagging.

**Comment by Sealjay** [comment]
I thought I'd share this tracked list of community events too, a good resource for finding upcoming conferences:
https://techcommunitycalendar.com/
