### ISSUE TITLE
Google Analytics for the Speakers website

### ISSUE THREAD

**Issue by holanita** [Green-Software-Foundation/speakers#46]
Hey @osamajandali can you add the Speakers website to our Google Analytics dashboard? Unsure if you've been tracking the traffic on those pages, but it would be nice to have some insights.

**Comment by zanete** [comment]
@osamajandali yes, I can't see Speakers property in the analytics here: https://analytics.google.com/analytics/web/#/p345122628/reports/intelligenthome?params=_u..nav%3Dmaui

**Comment by osamajandali** [comment]
Done

**Comment by holanita** [comment]
@osamajandali can you take another look. the dashboard says 
_No data received from your website yet.
To start collecting data, make sure that your website is tagged using the Measurement ID:G-PD771JR6ZG_
I've been looking at the site lately, but it won't appear in the stats.

**Comment by osamajandali** [comment]
@holanita I will double check and get back to you soon

**Comment by osamajandali** [comment]
@holanita it should be there now

**Comment by holanita** [comment]
@osamajandali it is, I am starting to see my real-time data now. thanks!
