### ISSUE TITLE
Searching by location is inconsistent and you can't search a region.

### ISSUE THREAD

**Issue by jawache** [Green-Software-Foundation/speakers#48]
**Is your feature request related to a problem? Please describe.**

Searching by location is inconsistent and you can't search a region.

E.g. if you are based in France and someone is searching for speakers in Europe they have to search every country in Europe one at a time.

**Describe the solution you'd like**

Be able to search a 
City, e.g. Paris
Country, e.g. France
Continent, e.g. Europe

And it returns the right people.

I think the solution here might be to have a consistent location field, it has to contain City, Country, Continent, right now it seems to be filled how the user filled it out.

**Describe alternatives you've considered**

**Additional context**

**Comment by holanita** [comment]
@jawache this is now done
