### ISSUE TITLE
Talks are missing from profile

### ISSUE THREAD

**Issue by holanita** [Green-Software-Foundation/speakers#51]
Hey @osamajandali talks are not visible in this profile page. Can you help fix this?
https://speakers.greensoftware.foundation/speakers/ricardo-miron/
It might be the third url that has a tricky format. I've tried adding it two different formats, but none of them worked. 
https://twitter.com/publiccodenet/status/1493851060947107844?s=20&t=We-_evqMNYUkNudAaxpnvw
https://twitter.com/publiccodenet/status/1493851060947107844/photo/1

**Comment by osamajandali** [comment]
Hey @holanita 
it only needs to say `others` not `other`
I fixed it: https://github.com/Green-Software-Foundation/speakers/commit/5d7c3ee69b57c423b2188acc11ed849265dab01c

**Comment by holanita** [comment]
Oh I see. Sorry about that and thanks @osamajandali
