### ISSUE TITLE
Give more visibility to speakers / promote the project

### ISSUE THREAD

**Issue by holanita** [Green-Software-Foundation/speakers#52]
@NAMRATA-WOKE let's continue here the conversation if you feel the need:

As per your recent comment:
We should start a practice that makes it easier for the community to identify recently added speakers. People are not checking all the time, so we want to make sure we are pushing content out as much as possible to build interest and drive traffic to the Bureau catalogue. For folks who have been enlisted since the beginning, we can figure out a way to promote their profiles as well!

My feedback:
- we could definitely start a practice to introduce our speakers to the community / network
- I suggested earlier to do interviews with them, but let's come up with other ideas if needed
- we should not choose based on who signed up when, but based on which speaker would be interested for example
- we should give each speaker the same opportunity to participate in this, let's advertise this opportunity in our email list

Let me know what your plan is and then let's discuss and agree on next steps together. Thanks!
cc @jawache please add your comments or guidance if you can

**Comment by NAMRATA-WOKE** [comment]
@holanita what's involved in the process of signing up to join the Speakers Bureau? If it's a simple form submission that leads to a review, I suggest from this point forward we include a checkbox that they can tick to grant permission to the foundation to amplify their profile as part of our broader marketing and communication practice. 

If we don't want to give them an option and want the freedom to share their profile in our newsletter if we find it fitting based on our content strategy and email marketing agenda, then its a simple term they have to agree to that we can include as a mandatory check before they submit their profile.

**Comment by NAMRATA-WOKE** [comment]
@holanita is it possible to get access to the responses or a document that tracks the individuals who have said yes?

**Comment by NAMRATA-WOKE** [comment]
Thanks @holanita. 

For this project specifically, what does the project being on hold imply? Are we putting a pause on getting more speakers signed up? Are we no longer reviewing applications? I'm not sure what's entailed in project work so apologies if the question sounds silly. 

If the form submissions are not getting addressed in any way and practitioners who continue to sign up will not know the status of their "application", then marketing does need to stop, which means our KPIs need to reflect the pause we're taking. @jawache please advise.

**Comment by jawache** [comment]
@NAMRATA-WOKE you have permission to post any of the speaker pages to socials and newsletters. Each page has a custom image already created which is the image shown on socials when sharing, please try. If we need to course correct we will, you can't go too wrong with this.

@holanita lets keep our processes light, no need to include Anna at this stage 😁

**Comment by NAMRATA-WOKE** [comment]
Thanks all.

**Comment by NAMRATA-WOKE** [comment]
Update on this front: since we modified our newsletter format, holding on promoting new speakers in our newsletter until we get a better sense of how our newsletter format is performing. Exploring how we might be able to create speaker spotlights on a monthly basis. The BENEFITS of this new content stream would help: 

Build interest in the Green Software Speakers Bureau
Raise awareness about where green software is being mentioned/discussed 
Identify where in the tech and IT ecosystem Green Software is still absent in conversation 
Provide GSF a way to create more branded content
Amplify the contributions of software practitioners working to scale green software 

@jawache

**Comment by jawache** [comment]
I think it's good to hold off on this now until at least a new PM comes onboard to manage the speakers project.
