### ISSUE TITLE
Help with presentation of deck for State Of Open Con 23

### ISSUE THREAD

**Issue by holanita** [Green-Software-Foundation/speakers#54]
Why: Szymon and Dan are presenting at a conference in 2 weeks (State of Open Con 2023)
What: Jenya to apply the mandatory template (not GSF style) to the deck

Scope of Work:
- The slides will be shared by Tuesday (31st) morning (maybe even Monday but TBC)
- and Jenya should apply the mandatory template (not GSF style) by the following Tuesday (07/02)

**Comment by Jenya-design** [comment]
Hello @danuw @Willmish 
Let's move our discussion here
Please let me know when you have the feedback from the conference 
Thank you

**Comment by Jenya-design** [comment]
Hello @holanita 
Yes, please archive this ticket
