### ISSUE TITLE
Forward new applications to new PM

### ISSUE THREAD

**Issue by holanita** [Green-Software-Foundation/speakers#56]
@jawache just sent you guys an email about this. Adding this here as well so you can assign this task if needed.

Since there is no new PM working on the speakers project, I was wondering whether there will be anyone looking at the new applications on a daily basis. We have 3 google forms on the website, they are all saved [here](https://drive.google.com/drive/folders/1DUJCb0wppVy2Q-J81U7bpIYHeT9Ggb31). Every time someone completed any of these forms, I got an email notification. I was thinking maybe you could somehow make sure the email notifications are forwarded to the new PM google group for the time being.

**Comment by jawache** [comment]
@Stephaniestocker can you take a look at this please, make sure those forms send emails to pms@gsf

**Comment by adamj89** [comment]
Please could I be given access to these forms @Stephaniestocker
