### ISSUE TITLE
Design Contributors Program Site

### ISSUE THREAD

**Issue by zanete** [Green-Software-Foundation/speakers#58]
Background: https://docs.google.com/document/d/1VGiacYFkcbjohXL9TskcrhCN7iS8zudl0gaE8iJOfS4/edit 

Features required for the Contributors platform:
**Getting data in there** 

1. As a contributor I would like to be able to add myself to the contributors platform (via Github)
2. As a Contributor I want to be able to add my contributions by specifying [date, type of contribution [speaking, organising, writing], activity (what I did)] - similar to https://mvp.microsoft.com/en-us/PublicProfile/5004204?fullName=Chris%20Lloyd-Jones 
3. As a GSF team member I want to be notified that a contributor has added at least 4 contributions so that I could evaluate and mark them as recognised
4. As a contributor I would like to receive regular reminders to go and update my records in case information has changed

**Browsing**:

1. As a user I want to be able to see all details and contributors for a specific contributor

**Filtering & Search (should use Algolia)**

1. As a person who is looking for contributors I want to be able to find all writers
4. As a person who is looking for contributors I want to be able to find all people in Europe
5. As a person who is looking for contributors I want to be able to see what filtering options I have (preliminary: country, contribution type, experience level or ability to travel, all updates to see in the doc, + GSF Expert flag)
6.

**GSF Recognition** 

1. As a GSF team member I want to be able to evaluate contributors and mark them as "Recognised" (a flag)
2. As a user I want to see people who have been flagged as GSF Experts
3. As GSF team member I want the experts to be appearing at top of any lists / search results
4. As a GSF team member I don't want contributors to be able to mark them selves as "experts"
5. (phase 2) a dedicated site with JUST the experts

**Comment by osamajandali** [comment]
You can explore the updated [prototype](https://www.figma.com/proto/9HjtEpeF3kPXm3f4zEYIIA/Green-Software-Foundation-Website?page-id=1501%3A319&type=design&node-id=1501-445&viewport=1150%2C-1231%2C0.48&t=AYkbAYfA3YUcqxzF-1&scaling=min-zoom&starting-point-node-id=1501%3A445&mode=design) for a preview of the latest enhancements to the contributors website. The key UI enhancements include:

1. **Expert Card Styling**: Notably, the expert cards now have a distinct visual treatment. Hovering over the star icon reveals a tooltip displaying relevant information such as "Expert Contributor."

2. **Filters Panel**: To streamline contributors discovery, I introduced a Filters panel. You can explore its functionality by clicking on the filters button.

3. **Activity Timeline**: The "Previous Talks" section has been replaced with an "Activity" section. This new feature presents a dynamic activity timeline tailored to each contributor, providing a comprehensive overview of their engagement.

Regarding the other features:


> As a contributor I would like to be able to add myself to the contributors platform (via Github)

I feel that contibutors need to have an interface other than editing their own .md files. This will make sure that no bugs will occurs when updating the files. I can add in-page panel where contibutor and edit their own page directly from inside the page if there being authenticated using github.


> As a GSF team member I want to be notified that a contributor has added at least 4 contributions so that I could evaluate and mark them as recognised

We need to have a CRON job (A function that runs periodically) that automatically checks for certain criteria and send email to the manager with a notification about 4 contributions 

> As a contributor I would like to receive regular reminders to go and update my records in case information has changed

Again a CRON job here to send email periodically to the contributor

**Comment by adamj89** [comment]
Hey @osamajandali this is an awesome start!

1. Awesome stuff. @jawache what do you think, I'm thinking we should maybe even have this more visible on the card (maybe a strip at the top saying "Expert" or "Recognised Contributor") n.b. these tier names aren't finalised. 
2. That's awesome. 
3. Fantastic. Love the cateogrisation and timeline view.

Editing in the UI - love it if that's possible!
CRON jobs - sounds good to me.  Question: where would we hold the email details for the contributor? Currently these are separately held in a Google form. If we held emails on the site, how could we secure these so others can't see it?

**Comment by jawache** [comment]
@osamajandali / @adamj89:

RE: Workflow/Editing. I prefer the approach where they do have to edit their contributions and submit a pull request. The pull request then needs to go through an approval process @adamj89 internally. Once approved, we merge their PR, and the website will be reflected. These will all be people who know are experts in software, so making a PR should be easy.

RE: Contributions: @adamj89 can you provide a taxonomy of contributions, can we define them now? If we already know what (limited) types of contributions people can submit then it makes the design/dev process a lot easier. E.g.
- List their code PR's
- List some media (video, audio) etc... 
- Link to an article
- Link to a speaking slot at a public event (online, offline)
- ?? What other activities do we want to encourage (activities that support **our** OKRs)


RE: Website

- **Speaking isn't a major part of this website anymore.** This is a complete revamp of our website, speaking is just one contribution you can make, there will be many contributors who never speak. The URL won't be speakers anymore, the text and the top won't be speakers. will have a new log, and the menu will be completely different. You can start the design again.
- @osamajandali: The only way this works is if they have a YAML file, and they keep it updated with a list of contributions in date order (and have all their other info in the YAML).
- Here are some examples of other similar programs:
- [AWS Heroes](https://aws.amazon.com/developer/community/heroes/?community-heroes-all.sort-by=item.additionalFields.sortPosition&community-heroes-all.sort-order=asc&awsf.filter-hero-category=*all&awsf.filter-location=*all&awsf.filter-year=*all&awsf.filter-activity=*all)
- [Microsoft MVP](https://mvp.microsoft.com/MvpSearch)
- [Google Developer Expert](https://developers.google.com/community/experts/directory)

**Comment by zanete** [comment]
- Soft-Launching beginning of October 
- At Decarb will be public launch, announcing the experts
- Stick to PR and GH for data management

Distinguish between three tiers of contributors:
- **Inactive Contributors** - always appear last in listings / search results
- **Recognised Contributors** (validated and recognised, ones who have reached a certain level of contributions and keep their records up to date, like the blue check in our case the green star. The validation gets removed if they haven't kept their records up to date, might need automated reminders to update or else you're out. Need people to worry and be concerned). If they haven't updated their records, they don't get displayed.
- **Experts** (So much bigger, the pinnacle) - could be at the top in a separate panel from contributors, so that people would want to fight for this level

Also need a new logo with Jenya ( @adamj89 to action) 
Need new copy ( @adamj89 to action with Jasper)

Follow-up actions for Osama:
- [ ] Update the webpage title to Green Software Contributors
- [ ] Replace the CTAs at the top with a menu that takes people to other places like the Wiki - Become an Expert, Become a Contributor, "Submit a call for papers", "About"
- [ ] Update the intro copy to be just one sentence (to maximise the space for Expert showcasing)
- [ ] Investigate the solutions for a geo-location search that would enable searching [Miles / KM to location: ]
- [ ] Search only for Contributors
- [ ] Remove filters (for now until we have concrete things to filter on)
- [ ] Adjust the grid to show max 5 cards
- [ ] Make expert profile page VERY AMAZING

**Comment by zanete** [comment]
Capturing the status on the weekly call:
- @osamajandali is rethinking the design, will keep the style but the structure of the pages, especially the contributor details page to be more appealing to share.

**Comment by osamajandali** [comment]
Here is the [prototype](https://www.figma.com/proto/dC1GtPHxilEz2EJza7LXN6/Green-Software-Contributors?page-id=1801%3A9520&type=design&node-id=16-8817&viewport=-2669%2C958%2C0.24&t=n5CjJKxzKasE6a3N-1&scaling=scale-down-width&starting-point-node-id=16%3A8817&mode=design)
_Click on any expert card to see the contributor page_

Below is a rundown of the new features integrated:

1. **Filters and Search Functionality:**
   I have implemented filtering and search feature. By combining the two we can improve the search for contributor experience.

2. **Enhanced Expert Card and Page:**
   Experts are now visually distinguishable, making it easier to identify their contributions. Additionally, I will introduced an option to filter experts contributors from the filter panel.

3. **Contributor Duration Display:**
   To provide a better understanding of a contributor's involvement, I've added a "Contributor Since" date. This will effectively showcase the length of their contributions over the years.

4. **Badge System Implementation:**
   I've added new badge system. Contributors will now be able to earn and display badges for notable achievements. For instance, distinctions like "Speaker of the Year 2023" and "Writer of the Month" can be showcased.

5. **Clear Contribution Timeline:**
   Contributions are now presented within a comprehensible timeline structure. Each year is clearly sectioned, highlighting the specific moments when contributions took place.

6. **Visual Identification of Inactive Users:**
   Inactive users are now visually distinguishable. This feature will help in differentiating between active and inactive contributors at a glance.

P.S. It's important to note that the sections, filters, and contributions currently exist as dummy placeholders. I'd like to agree upon those specific elements that will help me determining the fields that need to be integrated as I proceed with the page development.

Remember, you also have the option to provide direct feedback on the Figma prototype.

**Comment by zanete** [comment]
Capturing status on the weekly call:
- @adamj89 to chat to @jawache about the functionality with the Inactive. On hold until then
- Established that the Experts page is a separate page and that @adamj89 will create a **separate issue** for that. @osamajandali to start working on the prototype for that (will have no filters and no other champions on there). maybe in a diff colour, e.g. gold. (as the priorities are not the same)
- consider breadcrumbs at a later stage when there is enough hierarchy to warrant the need. Currently only one level

**Comment by osamajandali** [comment]
Here is the updated [prototype](https://www.figma.com/file/dC1GtPHxilEz2EJza7LXN6/Green-Software-Contributors?type=design&node-id=1801%3A9520&mode=design&t=hmjQD6LxNtRNIkxe-1)
let me know your thoughts and let's agree upon it quickly so I can start development 
cc: @adamj89 @jawache @zanete

**Comment by zanete** [comment]
@adamj89 can you let us know how you'd like to get feedback from other team members at GSF / steering commitee / working group. 
As per @NAMRATA-WOKE , it would be helpful to show it to a few people and gather feedback from people who'd we'd like to be Experts on the site so that they can share what they'd be looking for

**Comment by zanete** [comment]
Capturing the status during weekly call:
- we can consider this stage complete, any future design changes would need to be actioned separately. Now development begins
