### ISSUE TITLE
[Setup] add link to text field

### ISSUE THREAD

**Issue by holanita** [Green-Software-Foundation/speakers#7]
https://github.com/Green-Software-Foundation/speakers/blob/1fc40df3cbfb6f4ae1813214694adf8e9612f972/docs/speakers/daniel-vaughan.mdx?plain=1#L37

@osamajandali can I make links clickable within these text fields?

**Comment by osamajandali** [comment]
It will introduce some issues if we do that. 
do you want me to add a field for personal websites inside the speaker card?

**Comment by holanita** [comment]
ok noted. yes please add it.

**Comment by osamajandali** [comment]
Now the website field is added.
