### ISSUE TITLE
Updating Profile and Activity Records

### ISSUE THREAD

**Issue by zanete** [Green-Software-Foundation/speakers#76]
- [x] @LieneKal - Continue migrating the basic profiles to new md structure by 23rd
- [x] @adamj89 - create an Activity submission form and ping @zanete for testing
- [x] @adamj89 - Email the existing speakers to ask to update their information using the Update Profile form and the Activities form -with a deadline to submit by **Monday the 23rd** (form link: https://airtable.com/appyYf5kvFUBmA8Ts/shrtG32BVsx7JZ8IT)
- [ ] @zanete - submit activites on Asim's behalf
- [x] @zanete - Hand the migrated md profiles to Osama - https://drive.google.com/drive/folders/1y8T7KBFisnvmJ-22phma4bje7xnpN4zm
- [x] @osamajandali - to record a video for how to update the records by the 24th of October (including how to check out and commit, for total github dummies)
- [x] @LieneKal - from the 25th, go through the updated profile records in AirTable: "Champions -> Profiles" and update the new md files and update the AirTable record to Committed to MD
- [x] @LieneKal - from 25th, go through the activities records in AirTable: "Champions -> Activities" and add to the corresponding md file (based on the github name)
- [x] @adamj89 / @zanete  - calculate the Tentative activity score based on the activities added via AirTable

**Comment by LieneKal** [comment]
@zanete @adamj89 basic profile migration completed. Do you need me to upload all the files to the Google Drive folder?

**Comment by zanete** [comment]
@LieneKal that's amazing! Yes , please, then we can give them to Osama tomorrow morning so we can test the site with all the champions in it! 💪🏽

**Comment by LieneKal** [comment]
@zanete All done! 👍

**Comment by zanete** [comment]
@zanete add @jawache activities!!
